#%RAML 1.0 DataType

description: Contact.
displayName: Contact
type: object
properties:
  name:
    required: true
    type: string
    minLength: 1
  phoneNumber:
    required: false
    type: string
    pattern: ^\d{10}$
  email:
    required: false
    type: string
    pattern: ^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$
example: !include ../examples/contact.json
