#%RAML 1.0 DataType

description: Contact result.
displayName: ContactResult
type: object
properties:
  contact:
    required: true
    type: !include ./contact.raml
example: !include ../examples/contactResult.json
