#%RAML 1.0 DataType

description: Contact Update.
displayName: ContactUpdate
type: object
properties:
  name:
    required: false
    type: string
    minLength: 1
  phoneNumber:
    required: false
    type: Number
    pattern: /^\d{10}$/
  email:
    required: false
    type: string
    pattern: /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/
example: !include ../examples/contactUpdate.json
