#%RAML 1.0 Library

usage: Provides access to defined data types.
types:
  Contact: !include ../dataTypes/contact.raml
  ContactResult: !include ../dataTypes/contactResult.raml
  ContactResults: !include ../dataTypes/contactResults.raml
  ContactUpdate: !include ../dataTypes/contactUpdate.raml
  Message: !include ../dataTypes/message.raml
  TokenMessage: !include ../dataTypes/tokenMessage.raml
  User: !include ../dataTypes/user.raml
  UserInfo: !include ../dataTypes/userInfo.raml
  UserResult: !include ../dataTypes/userResult.raml
  UserResults: !include ../dataTypes/userResults.raml
  UserUpdate: !include ../dataTypes/userUpdate.raml 
